fix: entrypoint error

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -94,11 +94,20 @@ services:
     volumes:
     - ./frontend/letsencrypt:/etc/letsencrypt  # 挂载证书目录
     - ./frontend/nginx/certbot/www:/var/www/certbot  # 用于 certbot 验证
-    entrypoint: >
-      sh -c "trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot --email ${LETSENCRYPT_EMAIL} --agree-tos --no-eff-email -d ${LETSENCRYPT_HOST} && break; sleep 12; done"
     environment:
       LETSENCRYPT_HOST: scarletborder.cn
       LETSENCRYPT_EMAIL: baishuibeef@gmail.com
+    entrypoint: >
+      sh -c "trap exit TERM; 
+      while :; do
+        if [ -z \"$LETSENCRYPT_EMAIL\" ]; then
+          echo 'Error: LETSENCRYPT_EMAIL is not set!';
+          exit 1;
+        fi;
+        certbot certonly --webroot -w /var/www/certbot --email $LETSENCRYPT_EMAIL --agree-tos --no-eff-email -d $LETSENCRYPT_HOST && break;
+        sleep 12h;
+      done"
+    restart: always
 
   frontend-release:
     build: 
